### ISSUE TITLE
Node from url decode error

### ISSUE THREAD

**Issue by Zhaotianzheng** [airborne007/v2sub#4]
我发现我这边加了订阅地址之后返回的node并不是标准格式的，所以需要调用老哥的padding_base64才可以正常使用。
也就是在parser_subscribe函数中修改：
```python
#from
node = utils.byte2str(base64.b64decode(node))
#to
node = utils.str2byte(node)
node = utils.byte2str(base64.b64decode(padding_base64(node)))
```
不知道是不是和我这边的版本有关系
我的python是3.8，别的版本我也不懂怎么看了。。

不知道这是不是普遍存在的问题还是我加的订阅本身不符合规范呀？

**Comment by airborne007** [comment]
应该是你的订阅的问题，我这边用`python3.8.10`试了下，没有问题

**Comment by airborne007** [comment]
我再试了下，加上你的方法处理下，也是可以更新成功的，我稍后更新下代码你再试试吧。

**Comment by Zhaotianzheng** [comment]
好嘞，谢啦~
